changed workflow to clean previous initialization

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -1,4 +1,4 @@
-name: 'Terraform'
+name: "Terraform"
 
 on: push
 
@@ -8,42 +8,42 @@ env:
 
 jobs:
   terraform:
-    name: 'Terraform'
+    name: "Terraform"
     runs-on: ubuntu-latest
 
-    # Use the Bash shell regardless whether the GitHub Actions runner is 
+    # Use the Bash shell regardless whether the GitHub Actions runner is
     # ubuntu-latest, macos-latest, or windows-latest
     defaults:
       run:
         shell: bash
 
     steps:
-    # Checkout the repository to the GitHub Actions runner
-    - name: Checkout
-      uses: actions/checkout@v3
+      # Checkout the repository to the GitHub Actions runner
+      - name: Checkout
+        uses: actions/checkout@v3
 
-    # Install the preferred version of Terraform CLI 
-    - name: Setup Terraform
-      uses: hashicorp/setup-terraform@v2
+      # Install the preferred version of Terraform CLI
+      - name: Setup Terraform
+        uses: hashicorp/setup-terraform@v2
 
-    #Clean previous initialization for remote backend
-    - name: Clean .terraform Directory
+      # Clean previous initialization for remote backend
+      - name: Clean .terraform Directory
+        id: rm
         run: rm -rf .terraform
 
+      # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
+      - name: Terraform Init
+        id: init
+        run: terraform init
 
-    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
-    - name: Terraform Init
-      id: init
-      run: terraform init
+      # Run a terraform fmt for push
+      - name: Terraform Format
+        id: fmt
+        run: terraform fmt -check
 
-    # Run a terraform fmt for push
-    - name: Terraform Format
-      id: fmt
-      run: terraform fmt -check
-
-    # Run a terraform validate
-    # Run even if formatting fails
-    - name: Terraform Validate
-      id: validate
-      if: (success() || failure())
-      run: terraform validate
+      # Run a terraform validate
+      # Run even if formatting fails
+      - name: Terraform Validate
+        id: validate
+        if: (success() || failure())
+        run: terraform validate
